name: Security Checks

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  secret-scan:
    name: Scan for hardcoded secrets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Run Gitleaks secret scan
        uses: gitleaks/gitleaks-action@dcedce43c6f43de0b836d1fe38946645c9c638dc 
        # Use a specific commit hash to ensure stability
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  workflow-security:
    name: Check GitHub Actions security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
            persist-credentials: false

      - name: Install zizmor
        run: pipx install zizmor

      - name: Run zizmor
        run: zizmor .github/workflows/security-checks.yaml

# Checks for AWS access keys, GitHub tokens, API keys,Passwords,Private keys,Database credentials
# Set to only check the security checks workflow file to avoid false positives from other workflows that may have secrets for testing purposes.